project_name: cronviz
release:
  mode: append
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/cronviz
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "cronviz-checksums.txt"
brews:
  - tap:
      owner: winebarrel
      name: homebrew-cronplan
    homepage: https://github.com/winebarrel/cronplan
    description: cronviz is a tool to visualize cron schedule.
    license: MIT
    install: |
      bin.install 'cronviz'
nfpms:
  - id: cronviz-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/cronplan
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: cronviz is a tool to visualize cron schedule.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
