version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: cronplan
    binary: cronplan
    dir: ./cmd/cronplan
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
  - id: cronmatch
    binary: cronmatch
    dir: ./cmd/cronmatch
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
  - id: cronviz
    binary: cronviz
    dir: ./cmd/cronviz
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
  - id: crongrep
    binary: crongrep
    dir: ./cmd/crongrep
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
  - id: cronskd
    binary: cronskd
    dir: ./cmd/cronskd
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
archives:
  - id: cronplan
    ids: [cronplan]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: cronmatch
    ids: [cronmatch]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: cronviz
    ids: [cronviz]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: crongrep
    ids: [crongrep]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: cronskd
    ids: [cronskd]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
homebrew_casks:
  - name: cronplan
    ids: [cronplan]
    repository:
      owner: winebarrel
      name: homebrew-cronplan
    homepage: https://github.com/winebarrel/cronplan
    description: cronplan is a tool to show next triggers for AWS cron expression.
    license: MIT
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronplan"]
          end
  - name: cronmatch
    ids: [cronmatch]
    repository:
      owner: winebarrel
      name: homebrew-cronplan
    homepage: https://github.com/winebarrel/cronplan
    description: cronmatch is a tool to check if datetime matches AWS cron expression.
    license: MIT
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronmatch"]
          end
  - name: cronviz
    ids: [cronviz]
    repository:
      owner: winebarrel
      name: homebrew-cronplan
    homepage: https://github.com/winebarrel/cronplan
    description: cronviz is a tool to visualize cron schedule.
    license: MIT
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronviz"]
          end
  - name: crongrep
    ids: [crongrep]
    repository:
      owner: winebarrel
      name: homebrew-cronplan
    homepage: https://github.com/winebarrel/cronplan
    description: crongrep is a tool to grep with cron expression.
    license: MIT
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crongrep"]
          end
  - name: cronskd
    ids: [cronskd]
    repository:
      owner: winebarrel
      name: homebrew-cronplan
    homepage: https://github.com/winebarrel/cronplan
    description: cronskd is a tool to show a schedule of cron expressions.
    license: MIT
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronskd"]
          end
nfpms:
  - id: cronplan-nfpms
    ids: [cronplan]
    file_name_template: "{{ .Binary }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/cronplan
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: cronplan is a tool to show next triggers for AWS cron expression.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
  - id: cronmatch-nfpms
    ids: [cronmatch]
    file_name_template: "{{ .Binary }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/cronplan
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: cronmatch is a tool to check if datetime matches AWS cron expression.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
  - id: cronviz-nfpms
    ids: [cronviz]
    file_name_template: "{{ .Binary }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/cronplan
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: cronviz is a tool to visualize cron schedule.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
  - id: crongrep-nfpms
    ids: [crongrep]
    file_name_template: "{{ .Binary }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/cronplan
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: crongrep is a tool to grep with cron expression.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
  - id: cronskd-nfpms
    ids: [cronskd]
    file_name_template: "{{ .Binary }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/cronplan
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: cronskd is a tool to show a schedule of cron expressions.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
