before:
  hooks:
    - go mod tidy
builds:
  - id: cronplan
    binary: cronplan
    main: ./cmd/cronplan
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
  - id: cronmatch
    binary: cronmatch
    main: ./cmd/cronmatch
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
  - id: cronviz
    binary: cronviz
    main: ./cmd/cronviz
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
archives:
  - id: cronplan
    builds: [cronplan]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: cronmatch
    builds: [cronmatch]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: cronviz
    builds: [cronviz]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
brews:
  - name: cronplan
    ids: [cronplan]
    tap:
      owner: winebarrel
      name: homebrew-cronplan
    homepage: https://github.com/winebarrel/cronplan
    description: cronplan is a tool to show next triggers for AWS cron expression.
    license: MIT
    install: |
      bin.install 'cronplan'
  - name: cronmatch
    ids: [cronmatch]
    tap:
      owner: winebarrel
      name: homebrew-cronplan
    homepage: https://github.com/winebarrel/cronplan
    description: cronmatch is a tool to check if datetime matches AWS cron expression.
    license: MIT
    install: |
      bin.install 'cronmatch'
  - name: cronviz
    ids: [cronviz]
    tap:
      owner: winebarrel
      name: homebrew-cronplan
    homepage: https://github.com/winebarrel/cronplan
    description: cronviz is a tool to visualize cron schedule.
    license: MIT
    install: |
      bin.install 'cronviz'
nfpms:
  - id: cronplan-nfpms
    builds: [cronplan]
    file_name_template: "{{ .Binary }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/cronplan
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: cronplan is a tool to show next triggers for AWS cron expression.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
  - id: cronmatch-nfpms
    builds: [cronmatch]
    file_name_template: "{{ .Binary }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/cronplan
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: cronmatch is a tool to check if datetime matches AWS cron expression.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
  - id: cronviz-nfpms
    builds: [cronviz]
    file_name_template: "{{ .Binary }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/cronplan
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: cronviz is a tool to visualize cron schedule.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
