before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/cronplan
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
brews:
  - tap:
      owner: winebarrel
      name: homebrew-cronplan
    homepage: https://github.com/winebarrel/cronplan
    description: cronplan is a tool to show next triggers for AWS cron expression.
    license: MIT
    install: |
      bin.install 'cronplan'
nfpms:
  - id: cronplan-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/cronplan
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: cronplan is a tool to show next triggers for AWS cron expression.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
